#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : invm-frameworks
Version  : 01.00.00.2007
Release  : 1
URL      : https://github.com/intel/invm-frameworks/archive/v01.00.00.2007.zip
Source0  : https://github.com/intel/invm-frameworks/archive/v01.00.00.2007.zip
Summary  : Framework for Storage I18N, CLI and CIM applications
Group    : Development/Tools
License  : BSD-3-Clause-Clear BSL-1.0
Requires: invm-frameworks-lib
BuildRequires : cmake
Patch1: 0001-Add-make-install-magic.patch

%description
Framework library supporting a subset of Internationalization (I18N)
functionality, storage command line interface (CLI) applications, storage
common information model (CIM) providers.

%package dev
Summary: dev components for the invm-frameworks package.
Group: Development
Requires: invm-frameworks-lib
Provides: invm-frameworks-devel

%description dev
dev components for the invm-frameworks package.


%package lib
Summary: lib components for the invm-frameworks package.
Group: Libraries

%description lib
lib components for the invm-frameworks package.


%prep
%setup -q -n invm-frameworks-01.00.00.2007
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510178255
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1510178255
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/invm-cim/AssociationFactory.h
/usr/include/invm-cim/AssociationMapper.h
/usr/include/invm-cim/Attribute.h
/usr/include/invm-cim/CimXml.h
/usr/include/invm-cim/CimomAdapter.h
/usr/include/invm-cim/CmpiAdapter.h
/usr/include/invm-cim/Exception.h
/usr/include/invm-cim/ExceptionBadAttribute.h
/usr/include/invm-cim/ExceptionBadParameter.h
/usr/include/invm-cim/ExceptionInvalidWqlQuery.h
/usr/include/invm-cim/ExceptionNoMemory.h
/usr/include/invm-cim/ExceptionNotSupported.h
/usr/include/invm-cim/ExceptionSystemError.h
/usr/include/invm-cim/IndicationService.h
/usr/include/invm-cim/Instance.h
/usr/include/invm-cim/InstanceFactory.h
/usr/include/invm-cim/InstanceFactoryCreator.h
/usr/include/invm-cim/IntelCmpiProvider.h
/usr/include/invm-cim/IntelToCmpi.h
/usr/include/invm-cim/Logger.h
/usr/include/invm-cim/NullInstanceFactory.h
/usr/include/invm-cim/ObjectPath.h
/usr/include/invm-cim/ObjectPathBuilder.h
/usr/include/invm-cim/ProviderFactory.h
/usr/include/invm-cim/StringUtil.h
/usr/include/invm-cim/Strings.h
/usr/include/invm-cim/Trace.h
/usr/include/invm-cim/Types.h
/usr/include/invm-cim/WqlConditional.h
/usr/include/invm-cim/WqlQuery.h
/usr/include/invm-cim/cmpi/cmpidt.h
/usr/include/invm-cim/cmpi/cmpift.h
/usr/include/invm-cim/cmpi/cmpimacs.h
/usr/include/invm-cim/cmpi/cmpios.h
/usr/include/invm-cim/cmpi/cmpipl.h
/usr/include/invm-cim/common_types.h
/usr/include/invm-cim/logging.h
/usr/include/invm-cim/revision.h
/usr/include/invm-cim/s_str.h
/usr/include/invm-cim/time_utilities.h
/usr/include/invm-cim/unicode_utilities.h
/usr/include/invm-cim/x_str.h
/usr/include/invm-cli/CliFrameworkTypes.h
/usr/include/invm-cli/CommandFilter.h
/usr/include/invm-cli/CommandSpec.h
/usr/include/invm-cli/CommandVerify.h
/usr/include/invm-cli/DuplicateTokenErrorResult.h
/usr/include/invm-cli/ErrorResult.h
/usr/include/invm-cli/FeatureBase.h
/usr/include/invm-cli/FeatureRef.h
/usr/include/invm-cli/Framework.h
/usr/include/invm-cli/HelpFeature.h
/usr/include/invm-cli/HelpResult.h
/usr/include/invm-cli/Lexer.h
/usr/include/invm-cli/Logger.h
/usr/include/invm-cli/NoInputErrorResult.h
/usr/include/invm-cli/NotImplementedErrorResult.h
/usr/include/invm-cli/ObjectListResult.h
/usr/include/invm-cli/OutputOptions.h
/usr/include/invm-cli/OutputOptionsValidator.h
/usr/include/invm-cli/ParseErrorResult.h
/usr/include/invm-cli/Parser.h
/usr/include/invm-cli/PropertyListResult.h
/usr/include/invm-cli/ResultBase.h
/usr/include/invm-cli/SimpleListResult.h
/usr/include/invm-cli/SimpleResult.h
/usr/include/invm-cli/SyntaxErrorBadValueResult.h
/usr/include/invm-cli/SyntaxErrorMissingValueResult.h
/usr/include/invm-cli/SyntaxErrorResult.h
/usr/include/invm-cli/SyntaxErrorUnexpectedValueResult.h
/usr/include/invm-cli/Trace.h
/usr/include/invm-cli/cr_i18n.h
/usr/include/invm-cli/osAdapter.h
/usr/include/invm-i18n/libIntel_i18n.h
/usr/include/invm-i18n/system.h
/usr/lib/libinvm-cim.so
/usr/lib/libinvm-cli.so
/usr/lib/libinvm-i18n.so

%files lib
%defattr(-,root,root,-)
/usr/lib/libinvm-cim.so.1
/usr/lib/libinvm-cim.so.1.0.0
/usr/lib/libinvm-cli.so.1
/usr/lib/libinvm-cli.so.1.0.0
/usr/lib/libinvm-i18n.so.1
/usr/lib/libinvm-i18n.so.1.0.0
